name = "why2point4-images"
main = "./images.js"
compatibility_date = "2022-04-05" # https://developers.cloudflare.com/workers/platform/compatibility-dates/
usage_model = "bundled"
workers_dev = false

routes = [ "why2point4.com/images/*" ]

[[r2_buckets]]
binding = "R2"
bucket_name = "why2point4"
